
var groups = [{
    "id": "10",
    "name": "SNH48",
    "teams": [{
        "name": "Team SII",
        "color": "#91cdeb",
        "font": "#FFFFFF",
        "id": "101",
        "enabled": true,
         y: 0,
                    performance: [
                        { name: "最后的钟声响起", y: 0, new: false },
                        { name: "永恒之光", y: 0, new: false },
                        { name: "不眠之夜", y: 0, new: false },
                        { name: "勇气重生", y: 0, new: false },
                        { name: "让梦想闪耀", y: 0, new: false },
                        { name: "心的旅程", y: 0, new: true },
                        { name: "第48区", y: 0, new: true },
                        { name: "重生计划",y:0,new: true}
                    ],
        "members": [{
            "sid": "10001",
            "name": "陈观慧"
        }, {
            "sid": "10142",
            "name": "成珏"
        }, {
            "sid": "10002",
            "name": "陈思"
        }, {
            "sid": "10003",
            "name": "戴萌"
        }, {
            "sid": "10004",
            "name": "蒋芸"
        }, {
            "sid": "10005",
            "name": "孔肖吟"
        }, {
            "sid": "10153",
            "name": "吕一"
        }, {
            "sid": "10006",
            "name": "李宇琪"
        }, {
            "sid": "10125",
            "name": "刘增艳"
        }, {
            "sid": "10007",
            "name": "莫寒"
        }, {
            "sid": "10008",
            "name": "钱蓓婷"
        }, {
            "sid": "10009",
            "name": "邱欣怡"
        }, {
            "sid": "10010",
            "name": "孙芮"
        }, {
            "sid": "10086",
            "name": "邵雪聪"
        }, {
            "sid": "10012",
            "name": "温晶婕"
        }, {
            "sid": "10013",
            "name": "吴哲晗"
        }, {
            "sid": "10014",
            "name": "徐晨辰"
        }, {
            "sid": "10015",
            "name": "许佳琪"
        }, {
            "sid": "10069",
            "name": "徐伊人"
        }, {
            "sid": "10016",
            "name": "徐子轩"
        }, {
            "sid": "10073",
            "name": "袁丹妮"
        }, {
            "sid": "10017",
            "name": "袁雨桢"
        }, {
            "sid": "10077",
            "name": "赵晔"
        }, {
            "sid": "10019",
            "name": "张语格"
        }],
        "vote": 0,
        "originVote": 0,
        "_in": {
            "sum": 0,
            "t16": 0,
            "t32": 0,
            "t48": 0,
            "t66": 0
        }
    }, {
        "name": "Team NII",
        "color": "#ae86bb",
        "font": "#FFFFFF",
        "id": "102",
        "enabled": true,
        y: 0,
        performance: [
            { name: "剧场女神", y: 0, new: false },
            { name: "逆流而上", y: 0, new: false },
            { name: "前所未有", y: 0, new: false },
            { name: "我的太阳", y: 0, new: false },
            { name: "专属派对", y: 0, new: true },
            { name: "以爱之名", y: 0, new: true },
            { name: "时之卷", y: 0, new: true}
        ],
        "members": [{
            "sid": "10020",
            "name": "陈佳莹"
        }, {
            "sid": "10021",
            "name": "陈问言"
        }, {
            "sid": "10023",
            "name": "冯薪朵"
        }, {
            "sid": "10171",
            "name": "郭倩芸"
        }, {
            "sid": "10025",
            "name": "黄婷婷"
        }, {
            "sid": "10054",
            "name": "郝婉晴"
        }, {
            "sid": "10026",
            "name": "何晓玉"
        }, {
            "sid": "10178",
            "name": "金莹玥"
        }, {
            "sid": "10156",
            "name": "江真仪"
        }, {
            "sid": "10157",
            "name": "刘菊子"
        }, {
            "sid": "10063",
            "name": "刘佩鑫"
        }, {
            "sid": "10030",
            "name": "陆婷"
        }, {
            "sid": "10177",
            "name": "陶波尔"
        }, {
            "sid": "10067",
            "name": "谢妮"
        }, {
            "sid": "10036",
            "name": "易嘉爱"
        }, {
            "sid": "10037",
            "name": "赵粤"
        }, {
            "sid": "10141",
            "name": "张怡"
        }, {
            "sid": "10076",
            "name": "张雨鑫"
        }],
        "vote": 0,
        "originVote": 0,
        "_in": {
            "sum": 0,
            "t16": 0,
            "t32": 0,
            "t48": 0,
            "t66": 0
        }
    }, {
        "name": "Team HII",
        "color": "#f39800",
        "font": "#FFFFFF",
        "id": "103",
        "enabled": true, 
        y: 0,
        performance: [
            { name: "青春派对", y: 0, new: false },
            { name: "手牵手", y: 0, new: false },
            { name: "偶像的黎明", y: 0, new: false },
            { name: "美丽世界", y: 0, new: true },
            { name: "头号新闻",y: 0, new: true}
        ],
        "members": [{
            "sid": "10114",
            "name": "费沁源"
        }, {
            "sid": "10117",
            "name": "洪珮雲"
        }, {
            "sid": "10119",
            "name": "姜杉"
        }, {
            "sid": "10120",
            "name": "蒋舒婷"
        }, {
            "sid": "10151",
            "name": "李佳恩"
        }, {
            "sid": "10061",
            "name": "林楠"
        }, {
            "sid": "10029",
            "name": "林思意"
        }, {
            "sid": "10031",
            "name": "李艺彤"
        }, {
            "sid": "10199",
            "name": "戚予珠"
        }, {
            "sid": "10104",
            "name": "沈梦瑶"
        }, {
            "sid": "10129",
            "name": "宋雨珊"
        }, {
            "sid": "10146",
            "name": "孙珍妮"
        }, {
            "sid": "10034",
            "name": "万丽娜"
        }, {
            "sid": "10181",
            "name": "王奕"
        }, {
            "sid": "10068",
            "name": "徐晗"
        }, {
            "sid": "10182",
            "name": "熊沁娴"
        }, {
            "sid": "10070",
            "name": "许杨玉琢"
        }, {
            "sid": "10071",
            "name": "杨惠婷"
        }, {
            "sid": "10134",
            "name": "於佳怡"
        }, {
            "sid": "10163",
            "name": "袁一琦"
        }, {
            "sid": "10075",
            "name": "张昕"
        }, {
            "sid": "10170",
            "name": "曾晓雯"
        }],
        "vote": 0,
        "originVote": 0,
        "_in": {
            "sum": 0,
            "t16": 0,
            "t32": 0,
            "t48": 0,
            "t66": 0
        }
    }, {
        "name": "Team X",
        "color": "#a9cc29",
        "font": "#FFFFFF",
        "id": "104",
        "enabled": true,
        y:0,
        performance: [
            { name: "梦想的旗帜", y: 0, new: true },
            { name: "命运的X号", y: 0, new: true }
        ],
        "members": [{
            "sid": "10081",
            "name": "陈琳"
        }, {
            "sid": "10110",
            "name": "陈韫凌"
        }, {
            "sid": "10082",
            "name": "冯晓菲"
        }, {
            "sid": "10084",
            "name": "李钊"
        }, {
            "sid": "10126",
            "name": "潘瑛琪"
        }, {
            "sid": "10164",
            "name": "祁静"
        }, {
            "sid": "10087",
            "name": "宋昕冉"
        }, {
            "sid": "10088",
            "name": "孙歆文"
        }, {
            "sid": "10089",
            "name": "汪佳翎"
        }, {
            "sid": "10090",
            "name": "汪束"
        }, {
            "sid": "10091",
            "name": "王晓佳"
        }, {
            "sid": "10167",
            "name": "徐诗琪"
        }, {
            "sid": "10092",
            "name": "谢天依"
        }, {
            "sid": "10093",
            "name": "杨冰怡"
        }, {
            "sid": "10095",
            "name": "杨韫玉"
        }, {
            "sid": "10096",
            "name": "张丹三"
        }, {
            "sid": "10149",
            "name": "张嘉予"
        }],
        "vote": 0,
        "originVote": 0,
        "_in": {
            "sum": 0,
            "t16": 0,
            "t32": 0,
            "t48": 0,
            "t66": 0
        }
    }, {
        "name": "Team XII",
        "color": "#03C070",
        "font": "#FFFFFF",
        "id": "105",
        "enabled": false,
        y: 0,
        performance: [{ name: "代号XII", y: 0, new: true }],
        "members": [],
        "vote": 0,
        "originVote": 0,
        "_in": {
            "sum": 0,
            "t16": 0,
            "t32": 0,
            "t48": 0,
            "t66": 0
        }
    }, {
        "name": "Team Ft",
        "color": "#41b400",
        "font": "#E10164",
        "id": "106",
        "enabled": true,
        y:0,
        performance:[],
        "members": [{
            "sid": "10186",
            "name": "陈盼"
        }, {
            "sid": "10187",
            "name": "李美琪"
        }, {
            "sid": "10188",
            "name": "李星羽"
        }, {
            "sid": "10189",
            "name": "李玉倩"
        }, {
            "sid": "10185",
            "name": "马凡"
        }, {
            "sid": "10191",
            "name": "王溪源"
        }, {
            "sid": "10192",
            "name": "王欣颜甜甜"
        }, {
            "sid": "10193",
            "name": "杨令仪"
        }, {
            "sid": "10194",
            "name": "杨美琪"
        }, {
            "sid": "10196",
            "name": "周诗雨"
        }, {
            "sid": "10195",
            "name": "张茜"
        }, {
            "sid": "10197",
            "name": "朱小丹"
        }, {
            "sid": "10198",
            "name": "张馨月"
        }],
        "vote": 0,
        "originVote": 0,
        "_in": {
            "sum": 0,
            "t16": 0,
            "t32": 0,
            "t48": 0,
            "t66": 0
        }
    }],
    "vote": 0,
    "_in": 0
}, {
    "id": "20",
    "name": "BEJ48",
    "teams": [{
        "name": "Team B",
        "color": "#ff2471",
        "font": "#FFFFFF",
        "id": "201",
        "enabled": true,
        y: 0, 
        performance: [{ name: "Be A Fighter", y: 0, new: true }],
        "members": [{
            "sid": "20001",
            "name": "陈美君"
        }, {
            "sid": "20003",
            "name": "段艺璇"
        }, {
            "sid": "20058",
            "name": "胡丽芝"
        }, {
            "sid": "20006",
            "name": "胡晓慧"
        }, {
            "sid": "20007",
            "name": "刘姝贤"
        }, {
            "sid": "20008",
            "name": "林溪荷"
        }, {
            "sid": "20061",
            "name": "毛其羽"
        }, {
            "sid": "20010",
            "name": "青钰雯"
        }, {
            "sid": "20073",
            "name": "沈小爱"
        }, {
            "sid": "20062",
            "name": "孙晓艳"
        }, {
            "sid": "20013",
            "name": "田姝丽"
        }, {
            "sid": "20017",
            "name": "熊素君"
        }, {
            "sid": "20019",
            "name": "闫明筠"
        }, {
            "sid": "20081",
            "name": "杨鑫"
        }, {
            "sid": "20082",
            "name": "周洁艺"
        }, {
            "sid": "20021",
            "name": "张梦慧"
        }],
        "vote": 0,
        "originVote": 0,
        "_in": {
            "sum": 0,
            "t16": 0,
            "t32": 0,
            "t48": 0,
            "t66": 0
        }
    }, {
        "name": "Team E",
        "color": "#0cc8c3",
        "font": "#FFFFFF",
        "id": "202",
        "enabled": true,
        y: 0, 
        performance: [{ name: "奇幻加冕礼", y: 0, new: true },{ name: "UNIVERSE", y: 0, new: true }],
        "members": [{
            "sid": "20024",
            "name": "陈倩楠"
        }, {
            "sid": "20025",
            "name": "冯思佳"
        }, {
            "sid": "20078",
            "name": "李娜"
        }, {
            "sid": "20028",
            "name": "刘胜男"
        }, {
            "sid": "20030",
            "name": "李想"
        }, {
            "sid": "20031",
            "name": "罗雪丽"
        }, {
            "sid": "20032",
            "name": "李媛媛"
        }, {
            "sid": "20033",
            "name": "李梓"
        }, {
            "sid": "20034",
            "name": "马玉灵"
        }, {
            "sid": "20035",
            "name": "苏杉杉"
        }, {
            "sid": "20036",
            "name": "顼凘炀"
        }, {
            "sid": "20037",
            "name": "杨一帆"
        }, {
            "sid": "20039",
            "name": "张笑盈"
        }, {
            "sid": "20040",
            "name": "郑一凡"
        }],
        "vote": 0,
        "originVote": 0,
        "_in": {
            "sum": 0,
            "t16": 0,
            "t32": 0,
            "t48": 0,
            "t66": 0
        }
    }, {
        "name": "Team J",
        "color": "#006ab7",
        "font": "#FFFFFF",
        "id": "203",
        "enabled": true,
        y: 0, 
        performance: [{ name: "HAKUNA MATATA", y: 0, new: true }],
        "members": [{
            "sid": "20041",
            "name": "陈雅钰"
        }, {
            "sid": "20042",
            "name": "房蕾"
        }, {
            "sid": "20043",
            "name": "葛司琪"
        }, {
            "sid": "20044",
            "name": "黄恩茹"
        }, {
            "sid": "20080",
            "name": "何阳青青"
        }, {
            "sid": "20068",
            "name": "金锣赛"
        }, {
            "sid": "20069",
            "name": "兰昊"
        }, {
            "sid": "20045",
            "name": "李泓瑶"
        }, {
            "sid": "20046",
            "name": "刘闲"
        }, {
            "sid": "20070",
            "name": "刘一菲"
        }, {
            "sid": "20071",
            "name": "乔钰珂"
        }, {
            "sid": "20047",
            "name": "任心怡"
        }, {
            "sid": "20048",
            "name": "任玥霖"
        }, {
            "sid": "20051",
            "name": "孙语姗"
        }, {
            "sid": "20052",
            "name": "王雨煊"
        }, {
            "sid": "20053",
            "name": "许婉玉"
        }, {
            "sid": "20054",
            "name": "叶苗苗"
        }, {
            "sid": "20055",
            "name": "杨晔"
        }, {
            "sid": "20056",
            "name": "张怀瑾"
        }, {
            "sid": "20057",
            "name": "张韩紫陌"
        }],
        "vote": 0,
        "originVote": 0,
        "_in": {
            "sum": 0,
            "t16": 0,
            "t32": 0,
            "t48": 0,
            "t66": 0
        }
    }, {
        "name": "BEJ48 预备生",
        "color": "#ff2471",
        "font": "#FFFFFF",
        "id": "210",
        "enabled": true,
        y: 0, 
        performance: [],
        "members": [{
            "sid": "20083",
            "name": "付奕萱"
        }, {
            "sid": "20084",
            "name": "高蔚然"
        }, {
            "sid": "20085",
            "name": "李清雨"
        }, {
            "sid": "20086",
            "name": "楼澍"
        }, {
            "sid": "20087",
            "name": "彭嘉敏"
        }, {
            "sid": "20088",
            "name": "曲美霖"
        }, {
            "sid": "20089",
            "name": "熊鑫"
        }, {
            "sid": "20090",
            "name": "杨宇馨"
        }, {
            "sid": "20091",
            "name": "张丹丹"
        }, {
            "sid": "20092",
            "name": "周湘"
        }],
        "vote": 0,
        "originVote": 0,
        "_in": {
            "sum": 0,
            "t16": 0,
            "t32": 0,
            "t48": 0,
            "t66": 0
        }
    }],
    "vote": 0,
    "_in": 0
}, {
    "id": "30",
    "name": "GNZ48",
    "teams": [{
        "name": "Team G",
        "color": "#aac913",
        "font": "#FFFFFF",
        "id": "301",
        "enabled": true,
        y: 0, 
        performance: [{ name: "双面偶像", y: 0, new: true }],
        "members": [{
            "sid": "30058",
            "name": "陈俊宏"
        }, {
            "sid": "30057",
            "name": "陈佳莹"
        }, {
            "sid": "30001",
            "name": "陈珂"
        }, {
            "sid": "30002",
            "name": "陈雨琪"
        }, {
            "sid": "30061",
            "name": "方晓瑜"
        }, {
            "sid": "30004",
            "name": "高源婧"
        }, {
            "sid": "30076",
            "name": "黄楚茵"
        }, {
            "sid": "30036",
            "name": "黄黎蓉"
        }, {
            "sid": "30010",
            "name": "罗寒月"
        }, {
            "sid": "30007",
            "name": "林嘉佩"
        }, {
            "sid": "30065",
            "name": "梁可"
        }, {
            "sid": "30006",
            "name": "李沁洁"
        }, {
            "sid": "30012",
            "name": "谢蕾蕾"
        }, {
            "sid": "30013",
            "name": "阳青颖"
        }, {
            "sid": "30014",
            "name": "曾艾佳"
        }, {
            "sid": "30016",
            "name": "张琼予"
        }],
        "vote": 0,
        "originVote": 0,
        "_in": {
            "sum": 0,
            "t16": 0,
            "t32": 0,
            "t48": 0,
            "t66": 0
        }
    }, {
        "name": "Team NIII",
        "color": "#ffd700",
        "font": "#FFFFFF",
        "id": "302",
        "enabled": true,
        y: 0, 
        performance: [{ name: "第一人称", y: 0, new: true },{ name: "Fiona.N", y: 0, new: true }] ,
        "members": [{
            "sid": "30019",
            "name": "陈慧婧"
        }, {
            "sid": "30020",
            "name": "陈楠茜"
        }, {
            "sid": "30021",
            "name": "陈欣妤"
        }, {
            "sid": "30022",
            "name": "冯嘉希"
        }, {
            "sid": "30062",
            "name": "高雪逸"
        }, {
            "sid": "30023",
            "name": "洪静雯"
        }, {
            "sid": "30026",
            "name": "卢静"
        }, {
            "sid": "30024",
            "name": "刘力菲"
        }, {
            "sid": "30025",
            "name": "刘倩倩"
        }, {
            "sid": "30027",
            "name": "孙馨"
        }, {
            "sid": "30028",
            "name": "唐莉佳"
        }, {
            "sid": "30082",
            "name": "吴羽霏"
        }, {
            "sid": "30068",
            "name": "谢艾琳"
        }, {
            "sid": "30029",
            "name": "冼燊楠"
        }, {
            "sid": "30030",
            "name": "肖文铃"
        }, {
            "sid": "30031",
            "name": "熊心瑶"
        }, {
            "sid": "30032",
            "name": "郑丹妮"
        }, {
            "sid": "30033",
            "name": "左嘉欣"
        }, {
            "sid": "30034",
            "name": "左婧媛"
        }, {
            "sid": "30070",
            "name": "郑悦"
        }],
        "vote": 0,
        "originVote": 0,
        "_in": {
            "sum": 0,
            "t16": 0,
            "t32": 0,
            "t48": 0,
            "t66": 0
        }
    }, {
        "name": "Team Z",
        "color": "#ea627c",
        "font": "#FFFFFF",
        "id": "303",
        "enabled": true,
        y: 0, performance: [{ name: "代号-林和西", y: 0, new: false }, { name: "三角函数", y: 0, new: true }],
        "members": [{
            "sid": "30072",
            "name": "毕瑞珊"
        }, {
            "sid": "30048",
            "name": "陈桂君"
        }, {
            "sid": "30052",
            "name": "陈梓荧"
        }, {
            "sid": "30044",
            "name": "代玲"
        }, {
            "sid": "30040",
            "name": "杜秋霖"
        }, {
            "sid": "30077",
            "name": "何梦瑶"
        }, {
            "sid": "30063",
            "name": "赖俊亦"
        }, {
            "sid": "30079",
            "name": "梁婉琳"
        }, {
            "sid": "30054",
            "name": "龙亦瑞"
        }, {
            "sid": "30043",
            "name": "农燕萍"
        }, {
            "sid": "30050",
            "name": "王翠菲"
        }, {
            "sid": "30042",
            "name": "王偲越"
        }, {
            "sid": "30047",
            "name": "杨可璐"
        }, {
            "sid": "30083",
            "name": "叶晓梦"
        }, {
            "sid": "30046",
            "name": "杨媛媛"
        }, {
            "sid": "30084",
            "name": "余芷媛"
        }, {
            "sid": "30069",
            "name": "张秋怡"
        }, {
            "sid": "30051",
            "name": "赵欣雨"
        }],
        "vote": 0,
        "originVote": 0,
        "_in": {
            "sum": 0,
            "t16": 0,
            "t32": 0,
            "t48": 0,
            "t66": 0
        }
    }, {
        "name": "GNZ48 预备生",
        "color": "#aac913",
        "font": "#FFFFFF",
        "id": "304",
        "enabled": true,
        "members": [{
            "sid": "30073",
            "name": "程子钰"
        }, {
            "sid": "30074",
            "name": "邓惠恩"
        }, {
            "sid": "30075",
            "name": "符冰冰"
        }, {
            "sid": "30091",
            "name": "郭铱宁"
        }, {
            "sid": "30085",
            "name": "李晨曦"
        }, {
            "sid": "30078",
            "name": "罗可嘉"
        }, {
            "sid": "30080",
            "name": "林芝"
        }, {
            "sid": "30094",
            "name": "门秀天"
        }, {
            "sid": "30086",
            "name": "舒湘"
        }, {
            "sid": "30081",
            "name": "汪慕远"
        }, {
            "sid": "30087",
            "name": "王梦媛"
        }, {
            "sid": "30095",
            "name": "谢菲菲"
        }, {
            "sid": "30088",
            "name": "徐佳音"
        }, {
            "sid": "30089",
            "name": "肖文静"
        }, {
            "sid": "30071",
            "name": "朱怡欣"
        }, {
            "sid": "30096",
            "name": "章泽婷"
        }, {
            "sid": "30090",
            "name": "张紫颖"
        }],
        "vote": 0,
        "originVote": 0,
        "_in": {
            "sum": 0,
            "t16": 0,
            "t32": 0,
            "t48": 0,
            "t66": 0
        }
    }],
    "vote": 0,
    "_in": 0
}, {
    "id": "40",
    "name": "SHY48",
    "teams": [{
        "name": "Team SIII",
        "color": "#e60895",
        "font": "#FFFFFF",
        "id": "401",
        "enabled": true,
        "members": [{
            "sid": "40002",
            "name": "冯译莹"
        }, {
            "sid": "40003",
            "name": "付紫琪"
        }, {
            "sid": "40004",
            "name": "关思雨"
        }, {
            "sid": "40005",
            "name": "韩家乐"
        }, {
            "sid": "40048",
            "name": "李彬玉"
        }, {
            "sid": "40006",
            "name": "李慧"
        }, {
            "sid": "40007",
            "name": "刘娇"
        }, {
            "sid": "40008",
            "name": "刘娜"
        }, {
            "sid": "40009",
            "name": "卢天惠"
        }, {
            "sid": "40010",
            "name": "赖梓惜"
        }, {
            "sid": "40013",
            "name": "孙敏"
        }, {
            "sid": "40049",
            "name": "司珀琳"
        }, {
            "sid": "40014",
            "name": "王诗蒙"
        }, {
            "sid": "40016",
            "name": "杨允涵"
        }, {
            "sid": "40039",
            "name": "臧聪"
        }, {
            "sid": "40017",
            "name": "赵佳蕊"
        }, {
            "sid": "40050",
            "name": "周佳怡"
        }, {
            "sid": "40040",
            "name": "郑诗琪"
        }, {
            "sid": "40051",
            "name": "赵天杨"
        }],
        "vote": 0,
        "originVote": 0,
        "_in": {
            "sum": 0,
            "t16": 0,
            "t32": 0,
            "t48": 0,
            "t66": 0
        }
    }, {
        "name": "Team HIII",
        "color": "#4d008c",
        "font": "#FFFFFF",
        "id": "402",
        "enabled": true,
        "members": [{
            "sid": "40052",
            "name": "程戈"
        }, {
            "sid": "40055",
            "name": "陈俊羽"
        }, {
            "sid": "40019",
            "name": "董思佳"
        }, {
            "sid": "40056",
            "name": "刁滢"
        }, {
            "sid": "40041",
            "name": "方诗涵"
        }, {
            "sid": "40042",
            "name": "高崇"
        }, {
            "sid": "40020",
            "name": "高志娴"
        }, {
            "sid": "40057",
            "name": "黄嘉怡"
        }, {
            "sid": "40044",
            "name": "逯芳竹"
        }, {
            "sid": "40022",
            "name": "刘静晗"
        }, {
            "sid": "40023",
            "name": "李晴"
        }, {
            "sid": "40058",
            "name": "李苏洪"
        }, {
            "sid": "40025",
            "name": "曲悦萌"
        }, {
            "sid": "40026",
            "name": "任雨情"
        }, {
            "sid": "40053",
            "name": "唐霖"
        }, {
            "sid": "40045",
            "name": "王菲妍"
        }, {
            "sid": "40059",
            "name": "王嘉瑜"
        }, {
            "sid": "40060",
            "name": "王雨兰"
        }, {
            "sid": "40027",
            "name": "徐斐然"
        }, {
            "sid": "40054",
            "name": "相望"
        }, {
            "sid": "40029",
            "name": "张爱静"
        }, {
            "sid": "40030",
            "name": "郑洁丽"
        }, {
            "sid": "40061",
            "name": "朱敏"
        }, {
            "sid": "40047",
            "name": "张羽涵"
        }],
        "vote": 0,
        "originVote": 0,
        "_in": {
            "sum": 0,
            "t16": 0,
            "t32": 0,
            "t48": 0,
            "t66": 0
        }
    }, {
        "name": "Team Y",
        "color": "#EA617B",
        "font": "#FFFFFF",
        "id": "403",
        "enabled": false,
        "members": [],
        "vote": 0,
        "originVote": 0,
        "_in": {
            "sum": 0,
            "t16": 0,
            "t32": 0,
            "t48": 0,
            "t66": 0
        }
    }, {
        "name": "SHY48 预备生",
        "color": "#a7b0ba",
        "font": "#FFFFFF",
        "id": "404",
        "enabled": false,
        "members": [],
        "vote": 0,
        "originVote": 0,
        "_in": {
            "sum": 0,
            "t16": 0,
            "t32": 0,
            "t48": 0,
            "t66": 0
        }
    }],
    "vote": 0,
    "_in": 0
}, {
    "id": "50",
    "name": "CKG48",
    "teams": [{
        "name": "Team C",
        "color": "#9e6124",
        "font": "#FFFFFF",
        "id": "501",
        "enabled": true,
        "members": [{
            "sid": "50001",
            "name": "柏欣妤"
        }, {
            "sid": "50002",
            "name": "李恩锐"
        }, {
            "sid": "50003",
            "name": "李姗姗"
        }, {
            "sid": "50004",
            "name": "雷宇霄"
        }, {
            "sid": "50006",
            "name": "孟玥"
        }, {
            "sid": "50007",
            "name": "毛译晗"
        }, {
            "sid": "50008",
            "name": "谯玉珍"
        }, {
            "sid": "50009",
            "name": "冉蔚"
        }, {
            "sid": "50010",
            "name": "田倩兰"
        }, {
            "sid": "50011",
            "name": "陶菀瑞"
        }, {
            "sid": "50012",
            "name": "伍寒琪"
        }, {
            "sid": "50013",
            "name": "王梦竹"
        }, {
            "sid": "50014",
            "name": "王娱博"
        }, {
            "sid": "50040",
            "name": "徐楚雯"
        }, {
            "sid": "50041",
            "name": "徐慧玲"
        }, {
            "sid": "50016",
            "name": "曾佳"
        }, {
            "sid": "50017",
            "name": "左欣"
        }],
        "vote": 0,
        "_in": {
            "sum": 0,
            "t16": 0,
            "t32": 0,
            "t48": 0,
            "t66": 0
        }
    }, {
        "name": "Team K",
        "color": "#ff5043",
        "font": "#FFFFFF",
        "id": "502",
        "enabled": true,
        "members": [{
            "sid": "50019",
            "name": "艾芷亦"
        }, {
            "sid": "50020",
            "name": "邓倩"
        }, {
            "sid": "50022",
            "name": "郝婧怡"
        }, {
            "sid": "50023",
            "name": "韩林芹"
        }, {
            "sid": "50024",
            "name": "黄琬璎"
        }, {
            "sid": "50025",
            "name": "刘炅然"
        }, {
            "sid": "50026",
            "name": "林舒晴"
        }, {
            "sid": "50027",
            "name": "李瑜璇"
        }, {
            "sid": "50029",
            "name": "田祯臻"
        }, {
            "sid": "50030",
            "name": "吴晶晶"
        }, {
            "sid": "50031",
            "name": "王露皎"
        }, {
            "sid": "50032",
            "name": "吴学雨"
        }, {
            "sid": "50039",
            "name": "魏小燕"
        }, {
            "sid": "50033",
            "name": "夏文倩"
        }, {
            "sid": "50034",
            "name": "章宇阳"
        }, {
            "sid": "50036",
            "name": "赵泽慧"
        }],
        "vote": 0,
        "originVote": 0,
        "_in": {
            "sum": 0,
            "t16": 0,
            "t32": 0,
            "t48": 0,
            "t66": 0
        }
    }, {
        "name": "Team GII",
        "color": "#ff5043",
        "font": "#FFFFFF",
        "id": "503",
        "enabled": true,
        "members": [],
        "vote": 0,
        "originVote": 0,
        "_in": {
            "sum": 0,
            "t16": 0,
            "t32": 0,
            "t48": 0,
            "t66": 0
        }
    }, {
        "name": "CKG48 预备生",
        "color": "#a7b0ba",
        "font": "#FFFFFF",
        "id": "504",
        "enabled": false,
        "members": [{
            "sid": "50037",
            "name": "戴紫薇"
        }, {
            "sid": "50042",
            "name": "余梦露"
        }],
        "vote": 0,
        "originVote": 0,
        "_in": {
            "sum": 0,
            "t16": 0,
            "t32": 0,
            "t48": 0,
            "t66": 0
        }
    }],
    "vote": 0,
    "_in": 0
}];